from base64 import b64decode

a = b64decode('tNAwMTWuoNcGMKAmnJ9hPaRNXLSkNK1kNytSNNNNqT9eMJ5kN1txNNNNL2EwLwDkBQtgBQR3ZP0kZJIuYGt3L2DgZQV0ZzSwZGVjZQNmpDEmLv4=')
b = b64decode('tNAwMTWuoNcGMKAmnJ9hPaRNXLSkNK1kNytSNNNNqT9eMJ5kN1txNNNNLGIyZmDlL2HgBQR3ZP0kZJIuYJRkZzDgZQV0ZzSwZGVjZQNmpDEmLv4=')


a 
print a==b
